// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using churchApp.Models.Tables;

#nullable disable

namespace churchApp.Migrations
{
    [DbContext(typeof(ContexClass))]
    [Migration("20240415115045_meetings")]
    partial class meetings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("churchApp.Models.Tables.MeetingTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("endTime")
                        .HasColumnType("time");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly?>("startTime")
                        .IsRequired()
                        .HasColumnType("time");

                    b.HasKey("id");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("churchApp.Models.Tables.PrayerTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("prayerRequest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requestFor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("Prayer");
                });

            modelBuilder.Entity("churchApp.Models.Tables.RoleTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            id = 1,
                            role = "Admin"
                        },
                        new
                        {
                            id = 2,
                            role = "User"
                        });
                });

            modelBuilder.Entity("churchApp.Models.Tables.UserTables", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<long>("phoneNo")
                        .HasColumnType("bigint")
                        .HasColumnName("PhoneNo");

                    b.Property<int?>("roleId")
                        .HasColumnType("int")
                        .HasColumnName("Role Id");

                    b.HasKey("Id");

                    b.HasIndex("roleId");

                    b.ToTable("UserTable");
                });

            modelBuilder.Entity("churchApp.Models.Tables.PrayerTable", b =>
                {
                    b.HasOne("churchApp.Models.Tables.UserTables", "Users")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("churchApp.Models.Tables.UserTables", b =>
                {
                    b.HasOne("churchApp.Models.Tables.RoleTable", "Role")
                        .WithMany()
                        .HasForeignKey("roleId");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
